### ISSUE TITLE
[retest] Currency model issue when pointing to apparel

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1320]
When pointing to apparel-uk, i get this message:
Currency CurrencyModel (8796093153313@25) is not supported by the current base store

This was also reported by Venelin in Walkers when trying to set up the beauty project. He said something about Spartacus expecting USD.

To make Spartacus work we add UDS as a supported currency and change default to USD in Backoffice. 

We'll set up a server for developing against apparel.

**Comment by KateChuen** [comment]
Needs spike. Talk to Bill.

**Comment by Xymmer** [comment]
should be fixed with 1343

**Comment by KateChuen** [comment]
Still getting this error. Should I be changing some kind of configuration?
![apparelUKSpa](https://user-images.githubusercontent.com/45409515/59061227-fb93e880-8870-11e9-8d7c-14d1582e504e.png)

**Comment by Xymmer** [comment]
fixed with #1343
