### ISSUE TITLE
iphone8+: PLP grid view has spacing issues

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3065]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to "Digital Cameras -> Shop all"
On PLP, click on the grid view icon

**Actual Result**
There doesn't seem to have a difference between grid and list view on an iphone. 
Except that the grid view has some spacing issues. 

![iphonePLP](https://user-images.githubusercontent.com/45409515/59302706-8bb3a280-8c62-11e9-9414-dda5b45fc1d7.jpeg)

**Comment by developpeurweb** [comment]
This issue got fixed in GH-2835 but pls re-test after aforementioned ticket has been merged

**Comment by developpeurweb** [comment]
This has been merged and seems to work fine in local with latest `develop`.
Please note this was tested in ModelT, so please wait until changes are deployed there to retest on a real device.

**Comment by KateChuen** [comment]
ccv2 was updated with beta release which was done on friday.
i tried there and i still see this issue.

**Comment by developpeurweb** [comment]
This look good on my end both Chrome and Safari on an Iphone7 (same screen size as 8). 
Please make sure to clear cache or open in an incognito window.

![IMG_2361](https://user-images.githubusercontent.com/15113219/59878991-b6df7580-9377-11e9-9bea-83fcd7cf3eea.JPG)
![IMG_2362](https://user-images.githubusercontent.com/15113219/59878992-b6df7580-9377-11e9-9b2b-be4a6f966186.JPG)

**Comment by KateChuen** [comment]
@developpeurweb I still see this issue (even after clearing cache & incognito). Did you go on the grid view on PLP page? 
Because the list view is fine. It's the grid view that has the issue.

**Comment by KateChuen** [comment]
I don't see the issue on modelT anymore (but the data has changed too). 
But can close the ticket for now.
