### ISSUE TITLE
Default Payment Method not selected automatically

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3607]
Default Payment Method should be autoselected when proceeding to checkout and reaching the Select Payment Method stage. The user should not have to select it.

Similar to #3473

**Comment by Zeyber** [comment]
Not sure where this was fixed but no longer seeing the issue. Can anybody QA to try replicate?

**Comment by KateChuen** [comment]
I've tested on dev2 and I still see this issue.
Only shipping address is selected by default. 
Payment method still not fixed.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3648

**Comment by RadhepS** [comment]
QA Steps:
Add atleast 1 payment method

1. Start order process
2. When you get to the payment details, your default card should automatically be selected.
3. Add another payment card, this new card should be selected after creating it
4. Start order process again
5. The default card should be selected
6. Selected the second card and press continue
7. Press the browser's back button, the second card should be selected

**Comment by giancorderoortiz** [comment]
I do see that for subsequent order processes, the default payment method is selected. So, it's a pass. 
Nevertheless, for the current order, qa step #3 does happen, and it's a bit confusing for the user (visually speaking). 
But yes, with this fix, the checkout process is much faster and streamlined. 🆗
